{
 "title": "Kafka Dashboard",
 "description": "Kafka resource usage and consumer lag overview",
 "tags": [ "Kafka" ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "broker",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_controllerstate{job=\"kafka\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_cluster_partition_replicascount{job=\"kafka\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Partitions Leader Per Broker",
   "type": "table",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "kafka_cluster_partition_replicascount{job=~\"kafka\",topic=~\"$topic\"}"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kafka_server_replicamanager_leadercount{job=~\"kafka\"})"
    }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "description": "Active Controllers",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount{job=~\"kafka\"})"
    }
   ]
  },
  {
   "title": "Bytes In / Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "In (-) / Out (+)" }
   ],
   "targets": [
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",instance=~\"$broker\",topic!=\"\"}[2m]))by(instance)",
     "legendFormat": "Bytes Out [{{instance}}]"
    },
    {
     "expr": "sum (rate(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",instance=~\"$broker\",topic!=\"\"}[2m]))by(instance)",
     "legendFormat": "Bytes In [{{instance}}]"
    }
   ]
  },
  {
   "title": "Total of Topics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_globaltopiccount{job=~\"kafka\"})"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "description": "Under Replicated Partitions",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_underreplicatedpartitions{job=~\"kafka\"})"
    }
   ]
  },
  {
   "title": "Online Partitions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_partitioncount{job=~\"kafka\"})"
    }
   ]
  },
  {
   "title": "Offline Partitions",
   "type": "stat",
   "description": "Offline Partitions",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_offlinepartitionscount{job=~\"kafka\"})"
    }
   ]
  },
  {
   "title": "Messages In Per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(increase(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic=\"\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(increase(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic=\"\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(topic)(increase(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic=\"\"}[$__interval]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short", "label": "Messages/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_messagesin_total{job=\"kafka\",topic!=\"\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_bytesin_total{job=\"kafka\",topic!=\"\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "bytes", "label": "Bytes/s" }
   ],
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_bytesout_total{job=\"kafka\",topic!=\"\"}[$__interval]))",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(topic) (kafka_log_size{job=\"kafka\",})",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Kafka log size by broker (disk space utilization)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by(instance) (kafka_log_size{job=\"kafka\",})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Consumer lag by group",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "kafka_consumergroup_lag_sum", "legendFormat": "{{consumergroup}}" }
   ]
  },
  {
   "title": "ISR expands by instance",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(rate(kafka_server_replicamanager_isrexpands_total[1m]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Underreplicated partitions by topic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod)(kafka_server_replicamanager_underreplicatedpartitions)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}