version: '3.7'

services:
  postgres:
    image: postgres:9.5-alpine
    container_name: postgres
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - hands-on-network

networks:
  hands-on-network:
    external:
      name: kafka_handson_network