version: '3.5'
services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.4.0
    hostname: opensearch-node1
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.type=single-node
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping`
      - "OPENSEARCH_JAVA_OPTS=-Xms1024m -Xmx1024m" # Set min and max JVM heap sizes to at least 50% of system RAM
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 19200:9200 # REST API
      - 19600:9600 # Performance Analyzer
    networks:
      - hands-on-network

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.4.0
    hostname: opensearch-dashboards
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch-node1:9200"]'
    networks:
      - hands-on-network

volumes:
  opensearch-data1:

networks:
  hands-on-network:
    external:
      name: kafka_handson_network